# training STL
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-0-e1 -tokenizer ./roberta-tokenizer/ -seed 0 -num_train_epochs 1 -batch_size 16 > ./outputs/copa_common_0_e1.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-42-e1 -tokenizer ./roberta-tokenizer/ -seed 42 -num_train_epochs 1 -batch_size 16 > ./outputs/copa_common_42_e1.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-123-e1 -tokenizer ./roberta-tokenizer/ -seed 123 -num_train_epochs 1 -batch_size 16 > ./outputs/copa_common_123_e1.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-1234-e1 -tokenizer ./roberta-tokenizer/ -seed 1234 -num_train_epochs 1 -batch_size 16 > ./outputs/copa_common_1234_e1.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-1-e1 -tokenizer ./roberta-tokenizer/ -seed 1 -num_train_epochs 1 -batch_size 16 > ./outputs/copa_common_1_e1.txt
CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-11-e1 -tokenizer ./roberta-tokenizer/ -seed 11 -num_train_epochs 1 -batch_size 16 > ./outputs/copa_common_11_e1.txt
CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-12345-e1 -tokenizer ./roberta-tokenizer/ -seed 12345 -num_train_epochs 1 -batch_size 16 > ./outputs/copa_common_12345_e1.txt
CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-111-e1 -tokenizer ./roberta-tokenizer/ -seed 111 -num_train_epochs 1 -batch_size 16 > ./outputs/copa_common_111_e1.txt

# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-0-e3 -tokenizer ./roberta-tokenizer/ -seed 0 -num_train_epochs 3 -batch_size 16 > ./outputs/copa_common_0_e3.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-42-e3 -tokenizer ./roberta-tokenizer/ -seed 42 -num_train_epochs 3 -batch_size 16 > ./outputs/copa_common_42_e3.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-123-e3 -tokenizer ./roberta-tokenizer/ -seed 123 -num_train_epochs 3 -batch_size 16 > ./outputs/copa_common_123_e3.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-1234-e3 -tokenizer ./roberta-tokenizer/ -seed 1234 -num_train_epochs 3 -batch_size 16 > ./outputs/copa_common_1234_e3.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-1-e3 -tokenizer ./roberta-tokenizer/ -seed 1 -num_train_epochs 3 -batch_size 16 > ./outputs/copa_common_1_e3.txt

CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-joci-111-e3 -tokenizer ./roberta-tokenizer/ -seed 111 -num_train_epochs 3 -batch_size 16 > ./outputs/joci_common_111_e3.txt
CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-joci-12345-e3 -tokenizer ./roberta-tokenizer/ -seed 12345 -num_train_epochs 3 -batch_size 16 > ./outputs/joci_common_12345_e3.txt
CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-joci-11-e3 -tokenizer ./roberta-tokenizer/ -seed 11 -num_train_epochs 3 -batch_size 16 > ./outputs/joci_common_11_e3.txt


# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-joci-0-e3 -tokenizer ./roberta-tokenizer/ -seed 0 -num_train_epochs 3 -batch_size 16 > ./outputs/joci_common_0_e3.txt
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-joci-42-e3 -tokenizer ./roberta-tokenizer/ -seed 42 -num_train_epochs 3 -batch_size 16 > ./outputs/joci_common_42_e3.txt
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-joci-123-e3 -tokenizer ./roberta-tokenizer/ -seed 123 -num_train_epochs 3 -batch_size 16 > ./outputs/joci_common_123_e3.txt
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-joci-1234-e3 -tokenizer ./roberta-tokenizer/ -seed 1234 -num_train_epochs 3 -batch_size 16 > ./outputs/joci_common_1234_e3.txt
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-joci-1-e3 -tokenizer ./roberta-tokenizer/ -seed 1 -num_train_epochs 3 -batch_size 16 > ./outputs/joci_common_1_e3.txt
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-joci-123-e10 -tokenizer ./roberta-tokenizer/ -seed 123 -num_train_epochs 10 -batch_size 16 > ./outputs/joci_common_123_e10.txt
# testing STL
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-joci-0-e3 -tokenizer ./roberta-tokenizer/ -seed 0 -batch_size 16 --filename joci_common_0_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-joci-1-e3 -tokenizer ./roberta-tokenizer/ -seed 1 -batch_size 16 --filename joci_common_1_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-joci-42-e3 -tokenizer ./roberta-tokenizer/ -seed 42 -batch_size 16 --filename joci_common_42_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-joci-123-e3 -tokenizer ./roberta-tokenizer/ -seed 123 -batch_size 16 --filename joci_common_123_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-joci-1234-e3 -tokenizer ./roberta-tokenizer/ -seed 1234 -batch_size 16 --filename joci_common_1234_e3

# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-copa-0-e1 -tokenizer ./roberta-tokenizer/ -seed 0 -batch_size 16 --filename copa_common_0_e1
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-copa-1-e1 -tokenizer ./roberta-tokenizer/ -seed 1 -batch_size 16 --filename copa_common_1_e1
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-copa-42-e1 -tokenizer ./roberta-tokenizer/ -seed 42 -batch_size 16 --filename copa_common_42_e1
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-copa-123-e1 -tokenizer ./roberta-tokenizer/ -seed 123 -batch_size 16 --filename copa_common_123_e1
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-copa-1234-e1 -tokenizer ./roberta-tokenizer/ -seed 1234 -batch_size 16 --filename copa_common_1234_e1
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-joci-test-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 > ./joci_common_test_e1.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-joci-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./joci_common_e5.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-joci-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./joci_common_e10.txt
# python run_classification.py -train_data_path ../allCommon/mtl_common_all_train.txt -val_data_path ../allCommon/mtl_common_all_val.txt  -test_data_path ../allCommon/mtl_common_all_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-all-jdata-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 > ./outputs/all_common_jdata_e3.txt

# freeze from joci
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-joci-anli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-new-e3 --freeze > ./outputs/anli_common_freeze_joci_e3.txt
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-joci-hella-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-new-e3  --freeze > ./outputs/hella_common_freeze_joci_e3.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-joci-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load -load_dir ../roberta-common-joci-new-e3 --freeze > ./outputs/copa_common_freeze_joci_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-joci-atomic-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-new-e3 --freeze > ./outputs/atomic_common_freeze_joci_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-joci-social-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-new-e3 --freeze > ./outputs/social_common_freeze_joci_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-joci-snli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-new-e3 --freeze > ./outputs/snli_common_freeze_joci_e3.txt

# freeze to joci

# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-anli-joci-e3 -tokenizer ./roberta-tokenizer-old/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 --freeze > ./outputs/joci_common_freeze_anli_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-hella-joci-e3 -tokenizer ./roberta-tokenizer-old/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 --freeze > ./outputs/joci_common_freeze_hella_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-atomic-joci-e3 -tokenizer ./roberta-tokenizer-old/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 --freeze > ./outputs/joci_common_freeze_atomic_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-social-joci-e3 -tokenizer ./roberta-tokenizer-old/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-social-e3 --freeze > ./outputs/joci_common_freeze_social_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-snli-joci-e3 -tokenizer ./roberta-tokenizer-old/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-snli-e5 --freeze > ./outputs/joci_common_freeze_snli_e3.txt


# testing freeze to joci
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-anli-joci-e3 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_freeze_anli_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-hella-joci-e3 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_freeze_hella_e3

# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-atomic-joci-e3 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_freeze_atomic_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-social-joci-e3 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_freeze_social_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-snli-joci-e3 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_freeze_snli_e3


# testing freeze joci
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-joci-anli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename anli_common_freeze_joci_e3
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-joci-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename hella_common_freeze_joci_e3
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-joci-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_freeze_joci_e1
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-joci-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename atomic_common_freeze_joci_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-joci-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename social_common_freeze_joci_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-joci-snli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename snli_common_freeze_joci_e3


# python run_ts_classification.py -train_data_path ../allCommon/mtl_common_all_train_ti.txt -val_data_path ../allCommon/mtl_common_all_val_ti.txt  -test_data_path ./JOCI/mtl_common_all_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-all-ts-hetero-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 > ./outputs/all_common_ts_hetero_e3.txt

# testing old all common on all data with new joci
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-all-jdata-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_all_jdata_anli
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-all-jdata-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_all_jdata_hella
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-all-jdata-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_all_jdata_joci
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-all-jdata-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_all_jdata_copa
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-all-jdata-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_all_jdata_atomic
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-all-jdata-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_all_jdata_social
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-all-jdata-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_all_jdata_snli

# transfer learning from anli
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-anli-hella-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 > ./outputs/hella_common_transfer_anli_e1.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-anli-joci-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 > ./outputs/joci_common_transfer_anli_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-anli-atomic-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 > ./outputs/atomic_common_transfer_anli_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-anli-social-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 > ./outputs/social_common_transfer_anli_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-anli-snli-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 > ./outputs/snli_common_transfer_anli_e1.txt

# transfer learning from anli with freeze
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-anli-hella-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-anli-e3  --freeze > ./outputs/hella_common_freeze_anli_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-anli-joci-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 --freeze > ./outputs/joci_common_freeze_anli_e3.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-anli-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load -load_dir ../roberta-common-anli-e3 --freeze > ./outputs/copa_common_freeze_anli_e1.txt

# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-anli-atomic-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 --freeze > ./outputs/atomic_common_freeze_anli_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-anli-social-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 --freeze > ./outputs/social_common_freeze_anli_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-anli-snli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 --freeze > ./outputs/snli_common_freeze_anli_e3.txt


# # testing transfer learning from anli with freeze
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-anli-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename hella_common_freeze_anli_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-anli-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename joci_common_freeze_anli_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-anli-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_freeze_anli_e1
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-anli-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename atomic_common_freeze_anli_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-anli-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename social_common_freeze_anli_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-anli-snli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename snli_common_freeze_anli_e3


# # freeeze from atomic
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-atomic-anli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 --freeze > ./outputs/anli_common_freeze_atomic_e3.txt
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-atomic-hella-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3  --freeze > ./outputs/hella_common_freeze_atomic_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-atomic-joci-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 --freeze > ./outputs/joci_common_freeze_atomic_e3.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-atomic-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load -load_dir ../roberta-common-atomic-e3 --freeze > ./outputs/copa_common_freeze_atomic_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-atomic-social-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 --freeze > ./outputs/social_common_freeze_atomic_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-atomic-snli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 --freeze > ./outputs/snli_common_freeze_atomic_e3.txt

# # testing freeze atomic
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-atomic-anli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename anli_common_freeze_atomic_e3
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-atomic-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename hella_common_freeze_atomic_e3
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-atomic-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename joci_common_freeze_atomic_e3
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-atomic-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_freeze_atomic_e1
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-atomic-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename social_common_freeze_atomic_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-atomic-snli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename snli_common_freeze_atomic_e3


# # transfer learning from hella
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-anli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/anli_common_transfer_hella_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-joci-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/joci_common_transfer_hella_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-atomic-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/atomic_common_transfer_hella_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-social-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/social_common_transfer_hella_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-snli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/snli_common_transfer_hella_e3.txt


# # transfer learning from social
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-social-anli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-social-e3 > ./outputs/anli_common_transfer_social_e3.txt
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-social-hella-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-social-e3 > ./outputs/hella_common_transfer_social_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-social-joci-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-social-e3 > ./outputs/joci_common_transfer_social_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-social-atomic-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-social-e3 > ./outputs/atomic_common_transfer_social_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-social-snli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-social-e3 > ./outputs/snli_common_transfer_social_e3.txt


# testing
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16

# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-hella-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 > ./hella_common_e1.txt
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-hella-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./hella_common_e5.txt
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-hella-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./hella_common_e10.txt

# python run_classification.py -train_data_path ./defeasible/mtl_common_defeasible_train.txt -val_data_path ./defeasible/mtl_common_defeasible_val.txt  -test_data_path ./defeasible/mtl_common_defeasible_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-defeasible-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 > ./outputs/defeasible_common_e1.txt
# python run_classification.py -train_data_path ./defeasible/mtl_common_defeasible_train.txt -val_data_path ./defeasible/mtl_common_defeasible_val.txt  -test_data_path ./defeasible/mtl_common_defeasible_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-defeasible-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 > ./outputs/defeasible_common_e3.txt
# python run_classification.py -train_data_path ./defeasible/mtl_common_defeasible_train.txt -val_data_path ./defeasible/mtl_common_defeasible_val.txt  -test_data_path ./defeasible/mtl_common_defeasible_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-defeasible-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./outputs/defeasible_common_e5.txt
# python run_classification.py -train_data_path ./defeasible/mtl_common_defeasible_train.txt -val_data_path ./defeasible/mtl_common_defeasible_val.txt  -test_data_path ./defeasible/mtl_common_defeasible_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-defeasible-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./outputs/defeasible_common_e10.txt

# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-anli-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 > ./outputs/anli_common_e1.txt
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-anli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 > ./outputs/anli_common_e3.txt
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./outputs/anli_common_e5.txt
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-anli-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./outputs/anli_common_e10.txt

# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-snli-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 > ./outputs/snli_common_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-snli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 > ./outputs/snli_common_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-snli-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./outputs/snli_common_e5.txt

# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-social-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 > ./outputs/social_common_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-social-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 > ./outputs/social_common_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-social-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./outputs/social_common_e5.txt

# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-atomic-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 > ./outputs/atomic_common_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-atomic-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 > ./outputs/atomic_common_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-atomic-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./outputs/atomic_common_e5.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-atomic-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./outputs/atomic_common_e10.txt

# transfer learning
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-anli-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 > ./outputs/anli_common_e1.txt
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-tranfer-anli-hella-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 > ./hella_common_transfer_anli_hella_e1.txt


# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-anli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 > ./outputs/anli_common_e3.txt


# # testing
# testing transfer from social
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-social-anli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename anli_common_transfer_social_e3
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-social-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename hella_common_transfer_social_e3
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-social-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename joci_common_transfer_social_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-social-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename atomic_common_transfer_social_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-social-snli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename snli_common_transfer_social_e3


# # test anli e5
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_anli
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_hella
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_joci
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_copa
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_atomic
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_social
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_snli


# # test atomic on all data
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_anli
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_hella
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_joci
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_copa
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_atomic
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_social
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_snli

# # test social on all data
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_anli
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_hella
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_joci
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_copa
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_atomic
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_social
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_snli