# test hella on all data
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_joci
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_anli
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_copa
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_snli
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_atomic
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_social

# test joci on all data
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_hella
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_anli
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_copa
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_snli
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_atomic
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_social

# test anli on all data
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_anli
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_hella
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_joci
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_copa
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_atomic
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_social
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_snli

# test snli on all data
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-snli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_anli
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-snli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_hella
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-snli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_joci
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-snli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_copa
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-snli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_atomic
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-snli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_social
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-snli-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_snli

# # all data common
# python run_classification.py -train_data_path ./allCommon/mtl_common_all_train.txt -val_data_path ./allCommon/mtl_common_all_val.txt  -test_data_path ./allCommon/mtl_common_all_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-all-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./outputs/all_common_e5.txt
# # all data specific
# python run_specific_classification.py -train_data_path ./allSpecific/mtl_specific_all_train.txt -val_data_path ./allSpecific/mtl_specific_all_val.txt  -test_data_path ./allSpecific/mtl_specific_all_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-specific-all-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./outputs/all_specific_e5.txt


# # all data common
# python run_classification.py -train_data_path ./allCommon/mtl_common_all_train.txt -val_data_path ./allCommon/mtl_common_all_val.txt  -test_data_path ./allCommon/mtl_common_all_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-all-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./outputs/all_common_e10.txt
# # all data specific
# python run_specific_classification.py -train_data_path ./allSpecific/mtl_specific_all_train.txt -val_data_path ./allSpecific/mtl_specific_all_val.txt  -test_data_path ./allSpecific/mtl_specific_all_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-specific-all-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./outputs/all_specific_e10.txt

# all data specific
# python run_specific_classification.py -train_data_path ./allSpecific/mtl_specific_all_train.txt -val_data_path ./allSpecific/mtl_specific_all_val.txt  -test_data_path ./allSpecific/mtl_specific_all_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-specific-all-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 > ./outputs/all_specific_e3.txt

# # all data common
# python run_classification.py -train_data_path ./allCommon/mtl_common_all_train.txt -val_data_path ./allCommon/mtl_common_all_val.txt  -test_data_path ./allCommon/mtl_common_all_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-all-e15 -tokenizer ./roberta-tokenizer/ -num_train_epochs 15 -batch_size 16 > ./outputs/all_common_e15.txt
# # all data specific
# python run_specific_classification.py -train_data_path ./allSpecific/mtl_specific_all_train.txt -val_data_path ./allSpecific/mtl_specific_all_val.txt  -test_data_path ./allSpecific/mtl_specific_all_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-specific-all-e15 -tokenizer ./roberta-tokenizer/ -num_train_epochs 15 -batch_size 16 > ./outputs/all_specific_e15.txt


# # all data common
# python run_classification.py -train_data_path ./allCommon/mtl_common_all_train.txt -val_data_path ./allCommon/mtl_common_all_val.txt  -test_data_path ./allCommon/mtl_common_all_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-all-e20 -tokenizer ./roberta-tokenizer/ -num_train_epochs 20 -batch_size 16 > ./outputs/all_common_e20.txt
# # all data specific
# python run_specific_classification.py -train_data_path ./allSpecific/mtl_specific_all_train.txt -val_data_path ./allSpecific/mtl_specific_all_val.txt  -test_data_path ./allSpecific/mtl_specific_all_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-specific-all-e20 -tokenizer ./roberta-tokenizer/ -num_train_epochs 20 -batch_size 16 > ./outputs/all_specific_e20.txt

# # transfer learning from snli
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-snli-hella-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-snli-e5 > ./outputs/hella_common_transfer_snli_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-snli-joci-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-snli-e5 > ./outputs/joci_common_transfer_snli_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-snli-atomic-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-snli-e5 > ./outputs/atomic_common_transfer_snli_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-snli-social-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-snli-e5 > ./outputs/social_common_transfer_snli_e3.txt
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-snli-anli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-snli-e5 > ./outputs/anli_common_transfer_snli_e3.txt

# transffer learning from anli
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-anli-hella-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 > ./outputs/hella_common_transfer_anli_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-anli-joci-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 > ./outputs/joci_common_transfer_anli_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-anli-atomic-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 > ./outputs/atomic_common_transfer_anli_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-anli-social-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 > ./outputs/social_common_transfer_anli_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-anli-snli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 > ./outputs/snli_common_transfer_anli_e3.txt


#testing allcommon
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-all-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_all_anli
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-all-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_all_hella
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-all-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_all_joci
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-all-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_all_copa
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-all-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_all_atomic
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-all-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_all_social
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-all-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_all_snli




# testing transfer anli
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-anli-hella-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename hella_common_transfer_anli_e1
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-anli-joci-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename joci_common_transfer_anli_e1
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-anli-atomic-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename atomic_common_transfer_anli_e1
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-anli-social-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename social_common_transfer_anli_e1
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-anli-snli-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename snli_common_transfer_anli_e1

# transfer learning from hella
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-hella-anli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename anli_common_transfer_hella_e3
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-hella-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename joci_common_transfer_hella_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-hella-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename atomic_common_transfer_hella_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-hella-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename social_common_transfer_hella_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-hella-snli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename snli_common_transfer_hella_e3

# testing transfer from snli
python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-snli-anli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename anli_common_transfer_snli_e3
python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-snli-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename hella_common_transfer_snli_e3
python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-snli-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename joci_common_transfer_snli_e3
python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-snli-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename atomic_common_transfer_snli_e3
python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-snli-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename social_common_transfer_snli_e3



