# python run_classification.py -train_data_path ./aNLI/mtl_specific_anli_train.txt -val_data_path ./aNLI/mtl_specific_anli_val.txt  -test_data_path ./aNLI/mtl_specific_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-relative-anli-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 > ./outputs/anli_relative_e1.txt
# python run_classification.py -train_data_path ./HellaSwag/mtl_specific_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_specific_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_specific_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-relative-hella-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 > ./outputs/hella_relative_e1.txt

# python run_classification.py -train_data_path ./aNLI/mtl_specific_anli_train.txt -val_data_path ./aNLI/mtl_specific_anli_val.txt  -test_data_path ./aNLI/mtl_specific_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-relative-anli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 > ./outputs/anli_relative_e3.txt
# python run_classification.py -train_data_path ./HellaSwag/mtl_specific_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_specific_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_specific_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-relative-hella-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 > ./outputs/hella_relative_e3.txt


# python run_classification.py -train_data_path ./aNLI/mtl_specific_anli_train.txt -val_data_path ./aNLI/mtl_specific_anli_val.txt  -test_data_path ./aNLI/mtl_specific_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-relative-anli-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./outputs/anli_relative_e5.txt
# python run_classification.py -train_data_path ./HellaSwag/mtl_specific_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_specific_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_specific_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-relative-hella-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./outputs/hella_relative_e10.txt

# testing
# python run_classification.py -train_data_path ./aNLI/mtl_specific_anli_train.txt -val_data_path ./aNLI/mtl_specific_anli_val.txt  -test_data_path ./aNLI/mtl_specific_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-specific-anli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16

# test defeasible on all data
# python run_classification.py -train_data_path ./defeasible/mtl_common_defeasible_train.txt -val_data_path ./defeasible/mtl_common_defeasible_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-defeasible-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_anli
# python run_classification.py -train_data_path ./defeasible/mtl_common_defeasible_train.txt -val_data_path ./defeasible/mtl_common_defeasible_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-defeasible-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_hella
# python run_classification.py -train_data_path ./defeasible/mtl_common_defeasible_train.txt -val_data_path ./defeasible/mtl_common_defeasible_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-defeasible-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_joci
# python run_classification.py -train_data_path ./defeasible/mtl_common_defeasible_train.txt -val_data_path ./defeasible/mtl_common_defeasible_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-defeasible-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_copa
# python run_classification.py -train_data_path ./defeasible/mtl_common_defeasible_train.txt -val_data_path ./defeasible/mtl_common_defeasible_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-defeasible-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_atomic
# python run_classification.py -train_data_path ./defeasible/mtl_common_defeasible_train.txt -val_data_path ./defeasible/mtl_common_defeasible_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-defeasible-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_social
# python run_classification.py -train_data_path ./defeasible/mtl_common_defeasible_train.txt -val_data_path ./defeasible/mtl_common_defeasible_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-defeasible-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename common_snli

# # all data common
# python run_classification.py -train_data_path ./allCommon/mtl_common_all_train.txt -val_data_path ./allCommon/mtl_common_all_val.txt  -test_data_path ./allCommon/mtl_common_all_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-all-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 > ./outputs/all_common_e3.txt
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-hella-anli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename anli_common_transfer_hella_e3
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-hella-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename joci_common_transfer_hella_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-hella-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename atomic_common_transfer_hella_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-hella-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename social_common_transfer_hella_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-hella-snli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename snli_common_transfer_hella_e3

# transfer learning from atomic
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-anli-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/anli_common_transfer_atomic_e1.txt
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-hella-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/hella_common_transfer_atomic_e1.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-joci-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/joci_common_transfer_atomic_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-social-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/social_common_transfer_atomic_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-snli-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/snli_common_transfer_atomic_e1.txt

# # transfer learning from joci
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-joci-anli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-e3 > ./outputs/anli_common_transfer_joci_e3.txt
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-joci-hella-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-e3 > ./outputs/hella_common_transfer_joci_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-joci-atomic-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-e3 > ./outputs/atomic_common_transfer_joci_e3.txt
python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-joci-social-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-e3 > ./outputs/social_common_transfer_joci_e3.txt
python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-joci-snli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-e3 > ./outputs/snlli_common_transfer_joci_e3.txt

# testing transfer from joci
python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-joci-anli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename anli_common_transfer_joci_e3
python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-joci-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename hella_common_transfer_joci_e3
python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-joci-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename atomic_common_transfer_joci_e3
python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-joci-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename social_common_transfer_joci_e3
python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-joci-snli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename snli_common_transfer_joci_e3

