# # train STL on anli
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-anli-0-e3 -tokenizer ./roberta-tokenizer/ -seed 0 -num_train_epochs 3 -batch_size 16 > ./outputs/anli_common_0_e3.txt
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-anli-42-e3 -tokenizer ./roberta-tokenizer/ -seed 42 -num_train_epochs 3 -batch_size 16 > ./outputs/anli_common_42_e3.txt
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-anli-123-e3 -tokenizer ./roberta-tokenizer/ -seed 123 -num_train_epochs 3 -batch_size 16 > ./outputs/anli_common_123_e3.txt
#python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-anli-1234-e3 -tokenizer ./roberta-tokenizer/ -seed 1234 -num_train_epochs 3 -batch_size 16 > ./outputs/anli_common_1234_e3.txt
CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-anli-1-e3 -tokenizer ./roberta-tokenizer/ -seed 1 -num_train_epochs 3 -batch_size 16 > ./outputs/anli_common_1_e3.txt
CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-anli-11-e3 -tokenizer ./roberta-tokenizer/ -seed 11 -num_train_epochs 3 -batch_size 16 > ./outputs/anli_common_11_33.txt
CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-anli-111-e3 -tokenizer ./roberta-tokenizer/ -seed 111 -num_train_epochs 3 -batch_size 16 > ./outputs/anli_common_111_e3.txt
CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-anli-12345-e3 -tokenizer ./roberta-tokenizer/ -seed 12345 -num_train_epochs 3 -batch_size 16 > ./outputs/anli_common_12345_e3.txt


# # transfer learning from hella
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-anli-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/anli_common_transfer_hella_e1.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-joci-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/joci_common_transfer_hella_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-atomic-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/atomic_common_transfer_hella_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-social-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/social_common_transfer_hella_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-snli-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/snli_common_transfer_hella_e1.txt


# # transfer learning from atomic
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-hella-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/hella_common_transfer_atomic_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-joci-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/joci_common_transfer_atomic_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-social-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/social_common_transfer_atomic_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-snli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/snli_common_transfer_atomic_e3.txt
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-anli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/anli_common_transfer_atomic_e3.txt

# # test transfer learning from atomic
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-atomic-anli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename anli_common_transfer_atomic_e3
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-atomic-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename hella_common_transfer_atomic_e3
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-atomic-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename joci_common_transfer_atomic_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-atomic-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename social_common_transfer_atomic_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-atomic-snli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename snli_common_transfer_atomic_e3

# # transfer learning to copa
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 > ./outputs/copa_common_e3.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-joci-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-joci-e3 > ./outputs/copa_common_transfer_joci_e1.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-anli-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 > ./outputs/copa_common_transfer_anli_e1.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/copa_common_transfer_hella_e1.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/copa_common_transfer_atomic_e1.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-social-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-social-e3 > ./outputs/copa_common_transfer_social_e1.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-snli-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-snli-e5 > ./outputs/copa_common_transfer_snli_e1.txt

# transfer learning from joci
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-joci-anli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-new-e3 > ./outputs/anli_common_transfer_joci_e3.txt
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-joci-hella-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-new-e3 > ./outputs/hella_common_transfer_joci_e3.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-joci-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-joci-new-e3 > ./outputs/copa_common_transfer_joci_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-joci-atomic-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-new-e3 > ./outputs/atomic_common_transfer_joci_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-joci-social-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-new-e3 > ./outputs/social_common_transfer_joci_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-joci-snli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-joci-new-e3 > ./outputs/snli_common_transfer_joci_e3.txt

# transfer to joci
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-anli-joci-e3 -tokenizer ./roberta-tokenizer-old/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 > ./outputs/joci_common_transfer_anli_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-joci-e3 -tokenizer ./roberta-tokenizer-old/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/joci_common_transfer_hella_e3.txt

# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-joci-e3 -tokenizer ./roberta-tokenizer-old/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/joci_common_transfer_atomic_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-social-joci-e3 -tokenizer ./roberta-tokenizer-old/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-social-e3 > ./outputs/joci_common_transfer_social_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-snli-joci-e3 -tokenizer ./roberta-tokenizer-old/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-snli-e5 > ./outputs/joci_common_transfer_snli_e3.txt

# # testing transfer to joci
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-anli-joci-e3 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_transfer_anli_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-hella-joci-e3 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_transfer_hella_e3

# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-atomic-joci-e3 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_transfer_atomic_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-social-joci-e3 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_transfer_social_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-snli-joci-e3 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_transfer_snli_e3


# testing transfer from joci
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-joci-anli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename anli_common_transfer_joci_e3
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-joci-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename hella_common_transfer_joci_e3
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-joci-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_transfer_joci_e1

# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-joci-atomic-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename atomic_common_transfer_joci_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-joci-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename social_common_transfer_joci_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-joci-snli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename snli_common_transfer_joci_e3



# # testing copa on itself and transfer
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_e1
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-copa-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_e3

# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-anli-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_transfer_anli_e1
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-hella-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_transfer_hella_e1
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-joci-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_transfer_joci_e1
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-atomic-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_transfer_atomic_e1
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-social-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_transfer_social_e1
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-snli-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_transfer_snli_e1


# freeeze from atomic
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-atomic-anli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 --freeze > ./outputs/anli_common_freeze_atomic_e3.txt
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-atomic-hella-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3  --freeze > ./outputs/hella_common_freeze_atomic_e3.txt
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-atomic-joci-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 --freeze > ./outputs/joci_common_freeze_atomic_e3.txt
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-atomic-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load -load_dir ../roberta-common-atomic-e3 --freeze > ./outputs/copa_common_freeze_atomic_e1.txt
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-atomic-social-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 --freeze > ./outputs/social_common_freeze_atomic_e3.txt
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-freeze-atomic-snli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 --freeze > ./outputs/snli_common_freeze_atomic_e3.txt

# testing freeze atomic
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-atomic-anli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename anli_common_freeze_atomic_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-atomic-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename hella_common_freeze_atomic_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-atomic-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename joci_common_freeze_atomic_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-atomic-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_freeze_atomic_e1
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-atomic-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename social_common_freeze_atomic_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-freeze-atomic-snli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename snli_common_freeze_atomic_e3


# testing zero shot ffrom joci
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-anli-e3 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_anli_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-hella-e3 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_hella_e3

# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-atomic-e3 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_atomic_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-social-e3 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_social_e3
# CUDA_LAUNCH_BLOCKING=1 python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-snli-e5 -tokenizer ./roberta-tokenizer-old/ -batch_size 16 --filename joci_common_snli_e3
