# # transfer learning from hella
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-anli-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/anli_common_transfer_hella_e1.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-joci-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/joci_common_transfer_hella_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_train.txt -val_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_val.txt  -test_data_path ./defeasible/defeasible-atomic/mtl_common_atomic_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-atomic-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/atomic_common_transfer_hella_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-social-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/social_common_transfer_hella_e1.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-snli-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/snli_common_transfer_hella_e1.txt


# # transfer learning from atomic
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-hella-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/hella_common_transfer_atomic_e3.txt
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-joci-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/joci_common_transfer_atomic_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-social-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/social_common_transfer_atomic_e3.txt
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-snli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/snli_common_transfer_atomic_e3.txt
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-anli-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/anli_common_transfer_atomic_e3.txt

# # test transfer learning from atomic
# python run_classification.py -train_data_path ./aNLI/mtl_common_anli_train.txt -val_data_path ./aNLI/mtl_common_anli_val.txt  -test_data_path ./aNLI/mtl_common_anli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-atomic-anli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename anli_common_transfer_atomic_e3
# python run_classification.py -train_data_path ./HellaSwag/mtl_common_hellaswag_train.txt -val_data_path ./HellaSwag/mtl_common_hellaswag_val.txt  -test_data_path ./HellaSwag/mtl_common_hellaswag_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-atomic-hella-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename hella_common_transfer_atomic_e3
# python run_classification.py -train_data_path ./JOCI/mtl_common_joci_train.txt -val_data_path ./JOCI/mtl_common_joci_val.txt  -test_data_path ./JOCI/mtl_common_joci_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-atomic-joci-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename joci_common_transfer_atomic_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-social/mtl_common_social_train.txt -val_data_path ./defeasible/defeasible-social/mtl_common_social_val.txt  -test_data_path ./defeasible/defeasible-social/mtl_common_social_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-atomic-social-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename social_common_transfer_atomic_e3
# python run_classification.py -train_data_path ./defeasible/defeasible-snli/mtl_common_snli_train.txt -val_data_path ./defeasible/defeasible-snli/mtl_common_snli_val.txt  -test_data_path ./defeasible/defeasible-snli/mtl_common_snli_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-atomic-snli-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename snli_common_transfer_atomic_e3

# # transfer learning from joci
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-copa-e3 -tokenizer ./roberta-tokenizer/ -num_train_epochs 3 -batch_size 16 > ./outputs/copa_common_e3.txt

# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-joci-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-joci-e3 > ./outputs/copa_common_transfer_joci_e1.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-anli-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-anli-e3 > ./outputs/copa_common_transfer_anli_e1.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-hella-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-hella-e3 > ./outputs/copa_common_transfer_hella_e1.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-atomic-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-atomic-e3 > ./outputs/copa_common_transfer_atomic_e1.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-social-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-social-e3 > ./outputs/copa_common_transfer_social_e1.txt
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ../roberta-common-transfer-snli-copa-e1 -tokenizer ./roberta-tokenizer/ -num_train_epochs 1 -batch_size 16 --load --load_dir ../roberta-common-snli-e5 > ./outputs/copa_common_transfer_snli_e1.txt

# # testing copa on itself and transfer
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_e1
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-copa-e3 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_e3

# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-anli-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_transfer_anli_e1
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-hella-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_transfer_hella_e1
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-joci-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_transfer_joci_e1
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-atomic-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_transfer_atomic_e1
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-social-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_transfer_social_e1
# python run_classification.py -train_data_path ./COPA/mtl_common_copa_train.txt -val_data_path ./COPA/mtl_common_copa_val.txt  -test_data_path ./COPA/mtl_common_copa_test.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ../roberta-common-transfer-snli-copa-e1 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename copa_common_transfer_snli_e1





